name: parking_management_system
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ^3.1.1

dependencies:
  flutter:
    sdk: flutter
  english_words: ^4.0.0
  provider: ^6.0.0
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  firebase_storage: ^12.3.6
  cloud_firestore: ^5.4.4
  google_maps_flutter: ^2.9.0
  geolocator: ^13.0.1
  flutter_typeahead: ^5.2.0
  geocoding: ^3.0.0
  intl: ^0.19.0
  pdf: ^3.11.1
  path_provider: ^2.1.5
  image_picker: ^1.1.2
  open_file: ^3.5.9
  path: ^1.9.0
  flutter_datetime_picker: ^1.5.1
  timezone: ^0.10.0
  awesome_notifications: ^0.10.0
  flutter_chart_plus: any


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets: 
    - assets/logomelaka.jpg